site_name: kalle309 github page
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material-brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material-brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.tabs
custom_dir: overrides
nav:
  - Home: index.md
  - Now: now.md
plugins: []
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
